data "aws_availability_zones" "available" { state = "available" }
data "aws_ami" "ubuntu" { most_recent = true owners = ["099720109477"] filter { name = "name" values = ["ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*"] } filter { name = "virtualization-type" values = ["hvm"] } }
resource "aws_vpc" "main" { cidr_block = "10.20.0.0/16" enable_dns_support = true enable_dns_hostnames = true tags = { Name = "${var.project_name}-vpc" } }
resource "aws_internet_gateway" "igw" { vpc_id = aws_vpc.main.id tags = { Name = "${var.project_name}-igw" } }
resource "aws_subnet" "public_a" { vpc_id = aws_vpc.main.id cidr_block = "10.20.1.0/24" availability_zone = data.aws_availability_zones.available.names[0] map_public_ip_on_launch = true tags = { Name = "${var.project_name}-public-a" } }
resource "aws_subnet" "private_a" { vpc_id = aws_vpc.main.id cidr_block = "10.20.11.0/24" availability_zone = data.aws_availability_zones.available.names[0] tags = { Name = "${var.project_name}-private-a" } }
resource "aws_subnet" "private_b" { vpc_id = aws_vpc.main.id cidr_block = "10.20.12.0/24" availability_zone = data.aws_availability_zones.available.names[1] tags = { Name = "${var.project_name}-private-b" } }
resource "aws_route_table" "public" { vpc_id = aws_vpc.main.id route { cidr_block = "0.0.0.0/0" gateway_id = aws_internet_gateway.igw.id } tags = { Name = "${var.project_name}-public-rt" } }
resource "aws_route_table_association" "public_a" { subnet_id = aws_subnet.public_a.id route_table_id = aws_route_table.public.id }
resource "aws_security_group" "app" { name = "${var.project_name}-app-sg" description = "Application server access" vpc_id = aws_vpc.main.id ingress { from_port = 5000 to_port = 5000 protocol = "tcp" cidr_blocks = ["0.0.0.0/0"] } ingress { from_port = 22 to_port = 22 protocol = "tcp" cidr_blocks = ["0.0.0.0/0"] } egress { from_port = 0 to_port = 0 protocol = "-1" cidr_blocks = ["0.0.0.0/0"] } }
resource "aws_security_group" "db" { name = "${var.project_name}-db-sg" description = "MySQL only from application tier" vpc_id = aws_vpc.main.id ingress { from_port = 3306 to_port = 3306 protocol = "tcp" security_groups = [aws_security_group.app.id] } egress { from_port = 0 to_port = 0 protocol = "-1" cidr_blocks = ["0.0.0.0/0"] } }
resource "aws_db_subnet_group" "mysql" { name = "${var.project_name}-db-subnets" subnet_ids = [aws_subnet.private_a.id, aws_subnet.private_b.id] }
resource "aws_db_instance" "mysql" { identifier = "${var.project_name}-mysql" engine = "mysql" engine_version = "8.0" instance_class = "db.t3.micro" allocated_storage = 20 max_allocated_storage = 40 storage_type = "gp3" db_name = var.db_name username = var.db_username password = var.db_password port = 3306 db_subnet_group_name = aws_db_subnet_group.mysql.name vpc_security_group_ids = [aws_security_group.db.id] publicly_accessible = false skip_final_snapshot = true deletion_protection = false }
resource "aws_instance" "app" { ami = data.aws_ami.ubuntu.id instance_type = "t3.micro" subnet_id = aws_subnet.public_a.id vpc_security_group_ids = [aws_security_group.app.id] key_name = var.key_name associate_public_ip_address = true user_data = templatefile("${path.module}/user_data.sh", { db_host = aws_db_instance.mysql.address db_user = var.db_username db_password = var.db_password db_name = var.db_name }) tags = { Name = "${var.project_name}-app" } depends_on = [aws_db_instance.mysql] }
